<?php

/**
 * @file
 * Contains expert_questions.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function expert_questions_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the expert_questions module.
    case 'help.page.expert_questions':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Expert questions module') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function expert_questions_theme() {
  return [
    'expert_questions' => [
      'render element' => 'children',
    ],
  ];
}

/**
 * Implements hook_mail().
 */
function expert_questions_mail($key, &$message, $params) {
  $options = array(
    'langcode' => $message['langcode'],
  );

  switch ($key) {
    case 'expert_notify':
      $message['from'] = \Drupal::config('system.site')->get('mail');
      $message['subject'] = t('New questions on the site: @site', array('@site' => $params['site_name']), $options);
      $message['body'][] = $params['message'];
      break;
    case 'expert_notify_question':
      $message['from'] = \Drupal::config('system.site')->get('mail');
      $message['subject'] = t('A new question for the expert: @site', array('@site' => $params['site_name']), $options);
      $message['body'][] = $params['message'];
      break;
  }
}
